site_name: Synthetic Data Generators
site_description: Synthetic Data Generators for Python
site_author: "[Chris Mahoney](mailto:chris@mahoneyconsultingservices.com)"
site_dir: web
docs_dir: docs
remote_branch: docs-site
repo_name: synthetic-data-generators
repo_url: https://github.com/data-science-extensions/synthetic-data-generators
edit_uri: edit/main/docs/

watch:
  - src/synthetic_data_generators/
  - docs/
  - README.md

theme:
  name: material
  favicon: ./assets/images/python.svg
  coverpage_icon: ./assets/images/python.svg
  custom_dir: docs/overrides
  palette:
    primary: blue grey
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  logo: ./assets/images/python.svg
  icon:
    repo: material/gitlab
    edit: material/file-edit-outline
    view: material/file-eye-outline

nav:
  - Home: index.md
  - Usage:
      - Overview: usage/overview.md
      - Time Series:
        - Linear: usage/linear.md
  - Modules:
      - code/index.md
      - Time Series: code/time_series.md


markdown_extensions:
  - admonition
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: "🔗"
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version:
    provider: mike
    default: latest

extra_css:
  - assets/stylesheets/style.css
  - assets/stylesheets/admonitions.css
  - assets/stylesheets/code_chunks.css
  - https://site-assets.fontawesome.com/releases/v6.4.2/css/all.css

plugins:
  - search:
      lang: en
  - autorefs
  # - mkdocs-jupyter:
  #     # execute: true  #<-- enable for deployment
  #     execute: false  #<-- disable for testing
  #     include_source: true
  #     include_requirejs: true
  #     show_input: true
  #     no_input: false
  - mike:
      version_selector: true
      alias_type: copy
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            # extensions:
            #   - griffe_inherited_docstrings
            #   - docstring_inheritance.griffe
            allow_inspection: true
            docstring_style: google
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_source: true
            show_object_full_path: false
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_category_heading: true
            show_if_no_docstring: true
            heading_level: 3
            members_order: source
            group_by_category: false
            filters:
              - "!^__all__"
