name: CD

on:
  # Only trigger when release is published
  release:
    types:
      - published
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  test:

    name: Run Tests
    if: ${{ always() }}
    runs-on: ubuntu-latest

    permissions:
      contents: write  #<-- to allow push changes to the repository

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Git
        id: setup-git
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          make configure-git
          make git-switch-to-main-branch
          make git-refresh-current-branch

      - name: Install dependencies
        id: install-dependencies
        run: make install-all

      - name: Run checks
        id: run-checks
        run: make check

      - name: Copy coverage report
        id: copy-coverage-report
        run: make copy-coverage-report

      - name: Commit coverage report
        id: commit-coverage-report
        run: make commit-coverage-report

      - name: Upload coverage
        id: upload-coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov-report/xml/cov-report.xml
          verbose: true

  build-package:

      name: Build Package
      needs: test
      if: ${{ always() && needs.test.result == 'success' }}
      runs-on: ubuntu-latest

      permissions:
        contents: write  #<-- to allow assets to be uploaded to the release

      steps:

        - name: Checkout repository
          id: checkout-repository
          uses: actions/checkout@v4
          with:
            ref: main

        - name: Set up uv
          uses: astral-sh/setup-uv@v5

        - name: Setup Python
          id: setup-python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'

        - name: Check VERSION
          id: check-version
          env:
            VERSION: ${{ github.event.release.tag_name }}
          run: |
            if [ -z "${VERSION}" ]; then
              echo "/$VERSION is missing. Please try again."
              exit 1
            fi

        - name: Install dependencies
          run: make install

        - name: Setup Git
          id: setup-git
          env:
            GITHUB_ACTOR: ${{ github.actor }}
          run: |
            make configure-git
            make git-switch-to-main-branch
            make git-refresh-current-branch

        - name: Bump version
          id: bump-version
          env:
            VERSION: ${{ github.event.release.tag_name }}
          run: make bump-version

        - name: Update Git
          id: update-git
          env:
            VERSION: ${{ github.event.release.tag_name }}
          run: make update-git

        - name: Build package
          id: build-package
          run: make build-package

        - name: Upload assets
          id: upload-assets
          uses: softprops/action-gh-release@v2
          with:
            files: dist/*

        - name: Upload artifacts
          id: upload-artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: dist/*
            retention-days: 1
            overwrite: true

  deploy-package:

    name: Deploy to PyPI
    needs: build-package
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package
        id: publish-package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make publish-package

      - name: Check
        id: check
        run: |
          echo 'Package deployed to PyPI 👉 https://pypi.org/project/synthetic-data-generators/'
          uvx pip install --dry-run --no-deps --no-cache synthetic-data-generators

  install-package:

    name: Install Package on '${{ matrix.os }}' with '${{ matrix.python-version }}'
    needs: deploy-package

    if: ${{ always() && needs.deploy-package.result == 'success' }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
      fail-fast: false
      max-parallel: 15

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        id: install-package
        run: pip install --no-cache synthetic-data-generators

  build-docs:

    name: Build Docs
    needs:
      - test
      - deploy-package
    if: ${{ always() && needs.test.result == 'success' && needs.deploy-package.result == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write  #<-- to allow mike to push to the repository

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        id: install-dependencies
        run: make install-docs

      - name: Setup Git
        id: setup-git
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          make configure-git
          make git-switch-to-main-branch
          make git-refresh-current-branch

      - name: Build docs
        id: build-docs
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: make build-versioned-docs
